baseURL = 'https://sethfranklin.com/'
languageCode = 'en-us'
title = 'Seth Franklin'
theme = 'ananke'

sectionPagesMenu = "main"

[params]
mainSections = ["posts", "about"]
recent_posts_number = 3

[params.ananke.social.follow]
networks = [
  "youtube",
  "github",
  "linkedin"
]

[params.ananke.social.youtube]
username = "SethFranklin0"

[params.ananke.social.github]
username = "SethFranklin"

[params.ananke.social.linkedin]
username = "sethjfranklin"

[deployment]
  [[deployment.targets]]
    name = 'production'
    url = 'S3_BUCKET_URL'
