name: 'website'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'terraform'
    runs-on: ubuntu-latest
    environment: production

    env:
      TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
      TF_VAR_domain_name: ${{ secrets.TF_VAR_DOMAIN_NAME }}
      STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
      STATE_KEY: ${{ secrets.STATE_KEY }}

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: >
          terraform init
          -backend-config="bucket=$STATE_BUCKET"
          -backend-config="key=$STATE_KEY"
          -backend-config="region=$TF_VAR_aws_region"

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      - name: Output S3 bucket URL
        run: echo "S3_BUCKET_URL=$(terraform output s3_bucket_url | tr -d '"')" >> $GITHUB_OUTPUT

  hugo:
    needs: terraform
    name: 'hugo'
    runs-on: ubuntu-latest
    environment: production

    env:
      S3_BUCKET_URL: ${{ needs.terraform.outputs.S3_BUCKET_URL }}

    defaults:
      run:
        shell: bash
        working-directory: ./hugo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print S3 Bucket URL
        run: echo $S3_BUCKET_URL

      - name: Install hugo
        run: |
          curl -L "https://github.com/gohugoio/hugo/releases/download/v0.147.7/hugo_extended_withdeploy_0.147.7_linux-amd64.tar.gz" -o "hugo.tar.gz"
          mkdir hugo
          tar -xvzf hugo.tar.gz -C hugo
          echo "$(realpath hugo)" >> $GITHUB_PATH

      - name: Set S3 bucket target
        run: sed -i -e 's@S3_BUCKET_URL@'"$S3_BUCKET_URL"'@g' hugo.toml

      - name: Deploy Hugo site to S3 bucket
        run: hugo deploy
