name: 'website'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_aws_region: ${{ secrets.TF_VAR_AWS_REGION }}
  TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_CLOUDFLARE_API_TOKEN }}
  TF_VAR_domain_name: ${{ secrets.TF_VAR_DOMAIN_NAME }}
  STATE_BUCKET: ${{ secrets.STATE_BUCKET }}
  STATE_KEY: ${{ secrets.STATE_KEY }}

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  website:
    name: 'website'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./terraform
        run: >
          terraform init
          -backend-config="bucket=$STATE_BUCKET"
          -backend-config="key=$STATE_KEY"
          -backend-config="region=$TF_VAR_aws_region"

      - name: Terraform Format
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve -input=false

      - name: Output S3 bucket URL
        working-directory: ./terraform
        run: echo "S3_BUCKET_URL=$(terraform output s3_bucket_url | tr -d '"')" >> $GITHUB_ENV

      - name: Install hugo
        run: |
          curl -L "https://github.com/gohugoio/hugo/releases/download/v0.147.7/hugo_extended_withdeploy_0.147.7_linux-amd64.tar.gz" -o "hugo.tar.gz"
          mkdir hugo_bin
          tar -xvzf hugo.tar.gz -C hugo_bin
          echo "$(realpath hugo_bin)" >> $GITHUB_PATH

      - name: Set S3 bucket target
        working-directory: ./hugo
        run: sed -i -e 's@S3_BUCKET_URL@'"$S3_BUCKET_URL"'@g' hugo.toml

      - name: Build Hugo site
        working-directory: ./hugo
        run: hugo

      - name: Hugo deploy
        working-directory: ./hugo
        run: hugo deploy
